name: Parse-ENV
on:
  push:
  workflow_dispatch:
    inputs:
      ssh_host:
        description: "SSH Host"
        required: false
        default: ""
      ssh_user:
        description: "SSH User"
        required: false
        default: ""
      ssh_port:
        description: "SSH Port"
        required: false
        default: ""
      ssh_hostkey:
        description: "SSH Hostkey"
        required: false
        default: ""
      runner:
        description: "Select runner"
        required: true
        default: "windows-latest"
        type: choice
        options:
          - "svr2019-pg"
          - "svr2019-pg-actions-labs-01"
          - "svr2019-pg-actions-labs-02"
          - "windows-latest"
          - "windows-2022"
          - "windows-2019"
          - "ubuntu-latest"
          - "ubuntu-22.04"
          - "ubuntu-20.04"
jobs:
  Parse-ENV:
    name: Parse-ENV ${{ inputs.runner != '' && inputs.runner || 'windows-latest' }}
    runs-on: ${{ inputs.runner != '' && inputs.runner || 'windows-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # For Windows runners (using powershell)
      - name: Set environment variables using PowerShell (Windows)
        if: startsWith(runner.os, 'Windows')
        shell: powershell
        run: |
          # Call the script parse-env.ps1 based on OS
          ./scripts-yml/parse-env.ps1

      # For Linux runners (using pwsh)
      - name: Set environment variables using PowerShell (Linux)
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          # Call the script parse-env.ps1 based on OS
          ./scripts-yml/parse-env.ps1
