name: Parse-ENV

on:
  push:
  workflow_dispatch:
    inputs:
      ssh_host:
        description: "SSH Host"
        required: false
        default: ""
      ssh_user:
        description: "SSH User"
        required: false
        default: ""
      ssh_port:
        description: "SSH Port"
        required: false
        default: ""
      ssh_hostkey:
        description: "SSH Hostkey"
        required: false
        default: ""
      runner:
        description: "Select runner"
        required: true
        default: "windows-latest"
        type: choice
        options:
          - "windows-latest"
          - "windows-2022"
          - "windows-2019"
          - "ubuntu-latest"
          - "ubuntu-22.04"
          - "ubuntu-20.04"

jobs:
  Parse-ENV:
    name: Parse-ENV ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # For Windows runners (using PowerShell)
      - name: Set environment variables using PowerShell (Windows)
        if: startsWith(runner.os, 'Windows')
        shell: powershell
        run: |
          echo "INPUTS_JSON=${{ toJson(github.event.inputs) }}" >> $env:GITHUB_ENV
          # Call the script parse-env.ps1
          ./scripts-yml/parse-env.ps1

      # For Linux runners (using pwsh)
      - name: Set environment variables using PowerShell (Linux)
        if: runner.os == 'Linux'
        shell: pwsh
        run: |
          echo "INPUTS_JSON=${{ toJson(github.event.inputs) }}" >> $GITHUB_ENV
          # Call the script parse-env.ps1
          ./scripts-yml/parse-env.ps1
